### ISSUE TITLE
Flutter 2.0 + Null safe

### ISSUE THREAD

**Issue by bohdan1krokhmaliuk** [tastelessjolt/flutter_dynamic_icon#11]
Please update the package for flutter 2.0 and nullsafe

**Comment by nohli** [comment]
If you want null safety support right now, use

```
  flutter_dynamic_icon:
    git:
      url: https://github.com/nohli/flutter_dynamic_icon
      ref: migrate-to-null-safety
```

After updating the example app, I'll open a PR.
